name: Pull Request Workflow

on:
  pull_request:
    branches:
      - master
      - web-app

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install dependencies
        run: |
          pip install flask
          pip install keras
          pip install numpy
          pip install opencv-python
          pip3 install --upgrade tensorflow
          pip install pillow
