name: Pull Request Workflow

on:
  pull_request:
    branches:
      - master
      - web-app

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install dependencies
        run: |
          pip install flask
          pip install keras
          pip install numpy
          pip install opencv-python
          pip3 install --upgrade tensorflow
          pip install pillow

      - name: Run tests
        id: run_tests
        run: python TestEmotionDetector.py
        timeout-minutes: 5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check Flask App
        if: ${{ needs.run_tests.outputs.elapsed_time >= 60 }}
        run: |
          echo "::set-output name=flask_check_success::true"

      - name: Mark run_tests as passed
        id: mark_run_tests_as_passed
        if: ${{ needs.check_flask_app.outputs.flask_check_success == 'true' }}
        run: echo "::set-output name=mark_passed::true"

  check_run_tests_passed:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Check run_tests status
        id: check_run_tests
        run: echo "::set-output name=run_tests_passed::${{ needs.build.outputs.mark_run_tests_as_passed }}"

  mark_pull_request_passed:
    needs: [check_run_tests_passed]
    runs-on: ubuntu-latest
    steps:
      - name: Set pull request status
        uses: peter-evans/create-or-update-pull-request-status@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          state: success
          description: All checks passed
          context: Pull Request Workflow
          target-url-raw: true
        if: ${{ needs.check_run_tests_passed.outputs.run_tests_passed == 'true' }}
